package kx.simplecobblegen.blocks;

import java.util.List;

import net.minecraft.block.Block;
import net.minecraft.block.state.IBlockState;
import net.minecraft.client.util.ITooltipFlag;
import net.minecraft.client.resources.I18n;
import net.minecraft.item.ItemStack;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.util.text.TextFormatting;
import net.minecraft.world.World;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

import kx.simplecobblegen.tiles.TileEntityPushBlockGenerator;

/**
 *  The push variant of {@link BlockGenerator}. Adds another Tooltip 
 *  and changes the called Tile Entity in {@link Block#createTileEntity(World, IBlockState)} to the appropriate. 
 */
public class PushBlockGenerator extends BlockGenerator {
	/**
	 * Constructor.
	 * @param pName The Name used for the registry Name and the unlocalized Name
	 * @param pTier The Tier of the Block-Generator
	 * @param pMaterial The Block which will be generated by the Block-Generator
	 */
	public PushBlockGenerator(final String pName, final int pTier, final Block pMaterial) {
		super(pName, pTier, pMaterial);
	}

	@Override
	@SideOnly(Side.CLIENT)
	public void addInformation(final ItemStack stack, final World player, final List<String> tooltip, final ITooltipFlag advanced) {
		super.addInformation(stack, player, tooltip, advanced);
		tooltip.add(TextFormatting.YELLOW + I18n.format("simplecobblegen.tooltip.generator_3"));
	}

	@Override
	public TileEntity createTileEntity(final World world, final IBlockState state) {
		return new TileEntityPushBlockGenerator().setTierAndMaterial(this.tier, this.material);
	}
}
